DROP TABLE IF EXISTS ROLES;
CREATE TABLE ROLES (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  role_name varchar(25) NOT NULL,
  enable BOOLEAN DEFAULT TRUE NOT NULL
);

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name varchar (20) NOT NULL,
  surname varchar (30) NOT NULL,
  email varchar (20) UNIQUE NOT NULL,
  password varchar (200) NOT NULL,
  username varchar (30) NOT NULL,
  activated BOOLEAN DEFAULT FALSE NOT NULL,
  create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  role_id INT NOT NULL,
  CONSTRAINT fk_role FOREIGN KEY fk_role (role_id) REFERENCES ROLES (id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS POSTS;
CREATE TABLE POSTS (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title varchar (100) NOT NULL,
  description varchar (255),
  content LONGTEXT,
  resources TEXT,
  published BOOLEAN DEFAULT TRUE NOT NULL,
  create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  user_id INT NOT NULL,
  CONSTRAINT fk_user FOREIGN KEY fk_user (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id_post INT NOT NULL,
  id_user INT NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  comment MEDIUMTEXT,
  CONSTRAINT fks_user FOREIGN KEY fk_user (id_user) REFERENCES USERS (id) ON DELETE CASCADE,
  CONSTRAINT fks_posts FOREIGN KEY fks_posts (id_post) REFERENCES POSTS (id) ON DELETE CASCADE
);